name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Meteor-Client-Jar
          path: build/libs/*.jar
